### ISSUE TITLE
Test 4 del moodle non passato.

### ISSUE THREAD

**Issue by alessandro-massarenti** [RiccardoAgatea/Tutorato-Programmazione-2018-19#1]
Ho provato oggi ad usare questo codice sui test del moodle per capire bene come funziona e farne un reverse engineering, ma non riesce a passare il quarto dei 4 test.

Mi domandavo quindi come mai.

i test:

--- Program output ---
start
strato0
r0:1
r1:2

strato1
r0:1
r1:2

strato2
r0:1
r1:2

end

--- Expected output (text)---
start

strato0
r0:1
r1:2

strato1
r0:1
r1:0

strato2
r0:11
r1:22
end

**Comment by Facoch** [comment]
Mi stupisco che passasse gli altri test. Avevo dimenticato un importante aggiornamento del puntatore per i diversi strati. 

Guarda la nuova versione!
